load("@build_bazel_rules_swift//swift:swift.bzl", "swift_test")

filegroup(
    name = "extra_rules",
    srcs = [
        "ExtraRules.swift",
        "StandaloneObjCExtensionRule.swift",
    ],
    visibility = ["//visibility:public"],
)

swift_test(
    name = "StandaloneObjCExtensionRuleTests",
    srcs = ["StandaloneObjCExtensionRuleTests.swift"],
    module_name = "StandaloneObjCExtensionRuleTests",
    deps = [
        "@SwiftLint//:SwiftLintExtraRules",
    ],
)
