#import "SentryDefines.h"
#import "SentryGeo+Private.h"

#import "SentryLaunchProfiling+Tests.h"

#if SENTRY_TARGET_PROFILING_SUPPORTED
#    import "SentryContinuousProfiler+Test.h"
#    import "SentryMetricProfiler.h"
#    import "SentryProfilerDefines.h"
#    import "SentryProfilerMocksSwiftCompatible.h"
#    import "SentryProfilerSerialization+Test.h"
#    import "SentryProfilerSerialization.h"
#    import "SentryProfilerState.h"
#    import "SentryProfilerTestHelpers.h"
#    import "SentryTraceProfiler+Test.h"
#endif // SENTRY_TARGET_PROFILING_SUPPORTED

@import _SentryPrivate;

#import "NSMutableDictionary+Sentry.h"
#import "Sentry/Sentry-Swift.h"
#import "SentryClient+TestInit.h"
#import "SentryClient.h"
#import "SentryCrashStackEntryMapper.h"
#if !SDK_V10
#    import "SentryCrash+Test.h"
#    import "SentryCrashBinaryImageCache+Test.h"
#    import "SentryCrashBinaryImageCacheTestHelper.h"
#    import "SentryCrashCachedData.h"
#    import "SentryCrashCxaThrowSwapper.h"
#    import "SentryCrashDoctor.h"
#    import "SentryCrashJSONCodecObjC.h"
#    import "SentryCrashMachineContext.h"
#    import "SentryCrashMachineContext_Apple.h"
#    import "SentryCrashMonitor.h"
#    import "SentryCrashMonitorContext.h"
#    import "SentryCrashMonitor_MachException.h"
#    import "SentryCrashReport.h"
#    import "SentryCrashReportStore.h"
#    import "SentryCrashStackCursor_Backtrace.h"
#    import "SentryCrashStackCursor_SelfThread.h"
#endif
#import "SentryEnvelopeRateLimit.h"
#import "SentryFileManager+Test.h"
#import "SentryFormatter.h"
#import "SentryHttpStatusCodeRange+Private.h"
#import "SentryHttpTransport.h"
#import "SentryHub+Test.h"
#import "SentryInternalNotificationNames.h"
#import "SentryLogC.h"
#import "SentrySDKInternal+Tests.h"
#import "SentrySampleDecision+Private.h"
#import "SentrySpanInternal.h"
#import "SentrySwift.h"
#import "SentryTracer+Private.h"
#import "SentryTransportFactory.h"
#import "SentryWeakMap.h"
