#import "SentryDefines.h"

#import "SentryLaunchProfiling+Tests.h"

#if SENTRY_HAS_UIKIT
#    import "MockUIScene.h"
#    import "SentryDefaultUIViewControllerPerformanceTracker.h"
#    if SENTRY_TARGET_REPLAY_SUPPORTED
#        import "SentrySessionReplayIntegration+Private.h"
#        import "SentrySessionReplayIntegration+Test.h"
#    endif // SENTRY_TARGET_REPLAY_SUPPORTED
#    import "SentryUIEventTracker.h"
#    import "SentryUIEventTrackerTransactionMode.h"
#    import "SentryUIEventTrackingIntegration.h"
#    import "SentryUIViewControllerSwizzling+Test.h"
#    import "SentryUIViewControllerSwizzling.h"
#    import "UIViewController+Sentry.h"
#endif // SENTRY_HAS_UIKIT

#if SENTRY_TARGET_PROFILING_SUPPORTED
#    import "SentryContinuousProfiler+Test.h"
#    import "SentryContinuousProfiler.h"
#    import "SentryMetricProfiler.h"
#    import "SentryProfiler+Private.h"
#    import "SentryProfilerDefines.h"
#    import "SentryProfilerMocksSwiftCompatible.h"
#    import "SentryProfilerSerialization+Test.h"
#    import "SentryProfilerSerialization.h"
#    import "SentryProfilerState.h"
#    import "SentryProfilerTestHelpers.h"
#    import "SentryTraceProfiler+Test.h"
#endif // SENTRY_TARGET_PROFILING_SUPPORTED

@import _SentryPrivate;

#import "Helper/ExceptionCatcher.h"
#import "NSData+Unzip.h"
#import "NSLocale+Sentry.h"
#import "NSMutableDictionary+Sentry.h"
#import "PrivateSentrySDKOnly.h"
#import "Sentry/Sentry-Swift.h"
#import "SentryANRTrackerV1.h"
#import "SentryANRTrackerV2.h"
#import "SentryAppStartMeasurement+Private.h"
#import "SentryAppStartTracker.h"
#import "SentryAppStartTrackingIntegration.h"
#import "SentryArray.h"
#import "SentryAttachment+Private.h"
#import "SentryAutoBreadcrumbTrackingIntegration+Test.h"
#import "SentryAutoBreadcrumbTrackingIntegration.h"
#import "SentryBooleanSerialization.h"
#import "SentryBreadcrumb+Private.h"
#import "SentryBreadcrumbDelegate.h"
#import "SentryBreadcrumbTracker.h"
#import "SentryBuildAppStartSpans.h"
#import "SentryByteCountFormatter.h"
#import "SentryClassRegistrator.h"
#import "SentryClient+Private.h"
#import "SentryClient+TestInit.h"
#import "SentryConcurrentRateLimitsDictionary.h"
#import "SentryCoreDataSwizzling.h"
#import "SentryCoreDataTracker+Test.h"
#import "SentryCoreDataTrackingIntegration.h"
#import "SentryCrash+Test.h"
#import "SentryCrashBinaryImageCache.h"
#import "SentryCrashC.h"
#import "SentryCrashCachedData.h"
#import "SentryCrashCxaThrowSwapper.h"
#import "SentryCrashDebug.h"
#import "SentryCrashDefaultMachineContextWrapper.h"
#import "SentryCrashDoctor.h"
#import "SentryCrashInstallation+Private.h"
#import "SentryCrashInstallationReporter.h"
#import "SentryCrashIntegration+TestInit.h"
#import "SentryCrashIntegration.h"
#import "SentryCrashJSONCodecObjC.h"
#import "SentryCrashMachineContext.h"
#import "SentryCrashMachineContext_Apple.h"
#import "SentryCrashMonitor.h"
#import "SentryCrashMonitorContext.h"
#import "SentryCrashMonitor_AppState.h"
#import "SentryCrashMonitor_MachException.h"
#import "SentryCrashMonitor_System.h"
#import "SentryCrashReport.h"
#import "SentryCrashReportSink.h"
#import "SentryCrashReportStore.h"
#import "SentryCrashScopeHelper.h"
#import "SentryCrashScopeObserver.h"
#import "SentryCrashStackCursor_Backtrace.h"
#import "SentryCrashStackCursor_SelfThread.h"
#import "SentryCrashStackEntryMapper.h"
#import "SentryCrashUUIDConversion.h"
#import "SentryDataCategory.h"
#import "SentryDataCategoryMapper.h"
#import "SentryDateUtils.h"
#import "SentryDebugMeta.h"
#import "SentryDefaultAppStateManager.h"
#import "SentryDefaultThreadInspector.h"
#import "SentryDiscardReason.h"
#import "SentryDiscardReasonMapper.h"
#import "SentryEnvelopeAttachmentHeader.h"
#import "SentryEnvelopeRateLimit.h"
#import "SentryEvent+Private.h"
#import "SentryFileIOTrackerHelper.h"
#import "SentryFileIOTrackingIntegration.h"
#import "SentryFileManager+Test.h"
#import "SentryFileManagerHelper.h"
#import "SentryFormatter.h"
#import "SentryFrame.h"
#import "SentryFramesTrackingIntegration.h"
#import "SentryHttpStatusCodeRange+Private.h"
#import "SentryHttpTransport.h"
#import "SentryHub+Private.h"
#import "SentryHub+Test.h"
#import "SentryInitializeForGettingSubclassesNotCalled.h"
#import "SentryInstallation+Test.h"
#import "SentryInstallation.h"
#import "SentryInternalNotificationNames.h"
#import "SentryInvalidJSONString.h"
#import "SentryLevelMapper.h"
#import "SentryLogC.h"
#import "SentryLogTestHelper.h"
#import "SentryMechanism.h"
#import "SentryMechanismContext.h"
#import "SentryMeta.h"
#import "SentryNSDataUtils.h"
#import "SentryNSDictionarySanitize+Tests.h"
#import "SentryNSDictionarySanitize.h"
#import "SentryNSError.h"
#import "SentryNSURLSessionTaskSearch.h"
#import "SentryNetworkTracker.h"
#import "SentryNetworkTrackingIntegration.h"
#import "SentryNoOpSpan.h"
#import "SentryOptionsInternal.h"
#import "SentryPerformanceTracker+Testing.h"
#import "SentryPerformanceTracker.h"
#import "SentryPerformanceTrackingIntegration.h"
#import "SentryPredicateDescriptor.h"
#import "SentryProfilingConditionals.h"
#import "SentryQueueableRequestManager.h"
#import "SentrySDK+Private.h"
#import "SentrySDKInternal+Tests.h"
#import "SentrySampleDecision+Private.h"
#import "SentryScope+Private.h"
#import "SentryScopeSyncC.h"
#import "SentrySerialization.h"
#import "SentrySessionReplaySyncC.h"
#import "SentrySpan.h"
#import "SentrySpanDataKey.h"
#import "SentrySpanId.h"
#import "SentrySpanOperation.h"
#import "SentrySpotlightTransport.h"
#import "SentryStacktrace.h"
#import "SentryStacktraceBuilder.h"
#import "SentrySubClassFinder.h"
#import "SentrySwift.h"
#import "SentrySystemEventBreadcrumbs.h"
#import "SentrySystemWrapper.h"
#import "SentryTestIntegration.h"
#import "SentryTestObjCRuntimeWrapper.h"
#import "SentryThread.h"
#import "SentryTime.h"
#import "SentryTimeToDisplayTracker.h"
#import "SentryTraceOrigin.h"
#import "SentryTracePropagation.h"
#import "SentryTracer+Private.h"
#import "SentryTracer+Test.h"
#import "SentryTracerConfiguration.h"
#import "SentryTransaction.h"
#import "SentryTransactionContext+Private.h"
#import "SentryTransport.h"
#import "SentryTransportAdapter.h"
#import "SentryTransportFactory.h"
#import "SentryUncaughtNSExceptions.h"
#import "SentryUseNSExceptionCallstackWrapper.h"
#import "SentryViewHierarchyIntegration.h"
#import "SentryWatchdogTerminationBreadcrumbProcessor.h"
#import "SentryWeakMap.h"
#import "TestSentrySpan.h"
#import "TestSentryViewHierarchyProvider.h"
#import "URLSessionTaskMock.h"
