codecov:
  notify:
    after_n_builds: 2 # Wait for both iOS and Mac Catalyst to finish

coverage:
  range: "80...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "Sources/SentryCrash" 

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  after_n_builds: 2 # Wait for both iOS and Mac Catalyst to finish
