# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  - ".github/workflows/changes-in-high-risk-code.yml"
  - "Sources/Sentry/SentryNSURLSessionTaskSearch.m"
  - "Sources/Sentry/SentryNetworkTracker.m"
  - "Sources/Sentry/SentryUIViewControllerSwizzling.m"
  - "Sources/Sentry/SentryNSDataSwizzling.m"
  - "Sources/Sentry/SentryNSFileManagerSwizzling.m"
  - "Sources/Sentry/SentrySubClassFinder.m"
  - "Sources/Sentry/SentryCoreDataSwizzling.m"
  - "Sources/Sentry/SentrySwizzleWrapper.m"
  - "Sources/Sentry/include/SentrySwizzle.h"
  - "Sources/Sentry/SentrySwizzle.m"
  - "Sources/Sentry/SentryFileManager.m"
  - "Sources/Sentry/SentrySerialization.m"
  - "Sources/Sentry/SentrySerialization.h"

run_unit_tests_for_prs: &run_unit_tests_for_prs # Code
  - "Sources/**"
  - "Tests/**"
  - "SentryTestUtils/**"
  - "SentryTestUtilsDynamic/**"

  # GH Actions
  - ".github/workflows/test.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/sentry-xcodebuild.sh"
  - "scripts/tests-with-thread-sanitizer.sh"

  # Other
  - "test-server/**"
  - "Sentry.xcodeproj"
  - "**/*.xctestplan"
  - "fastlane/**"
  - ".codecov.yml"
  - "Brewfile*" # Dependency installation affects test environment
  - "Makefile" # Make commands used for CI build setup

run_api_stability_for_prs: &run_api_stability_for_prs # API-related code
  - "Sources/**"
  - "test-server/**"

  # GH Actions
  - ".github/workflows/api-stability.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # Scripts
  - "scripts/build-xcframework-local.sh"
  - "scripts/update-api.sh"
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"

  # Other
  - "Makefile" # Make commands used for API generation
  - "sdk_api.json"
  - "sdk_api_v9.json"

run_integration_test_for_prs: &run_integration_test_for_prs # CocoaPods integration test
  # GH Actions
  - ".github/workflows/integration-test.yml"
  - ".github/file-filters.yml"

  # Project files
  - "*.xcodeproj"
  - "*.xcworkspace"
  - "*.podspec"
  - "Plans/iOS-Cocoapods-Swift6_Base.xctestplan"

  # Sources
  - "Sources/**"
  - "Samples/iOS-Cocoapods-*/**"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"

  # Other
  - "fastlane/**"
  - "Gemfile.lock"

run_benchmarking_for_prs: &run_benchmarking_for_prs
  - "Sources/**"

  # Benchmarking implementation
  - "Samples/iOS-Swift/**"
  - ".sauce/benchmarking-config.yml"
  - "fastlane/**"

  # GH Actions
  - ".github/workflows/benchmarking.yml"
  - ".github/workflows/build-xcframework-variant-slices.yml"
  - ".github/workflows/assemble-xcframework-variant.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/assemble-xcframework.sh"

  # Project files
  - "Samples/iOS-Swift/iOS-Swift.yml"
  - "Samples/iOS-Swift/iOS-Swift.xcconfig"
  - "Samples/iOS-Swift/iOS-SwiftClip.xcconfig"
  - "Samples/iOS-Swift/iOS-Benchmarking.xcconfig"

run_test_cross_platform_for_prs: &run_test_cross_platform_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/test-cross-platform.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.podspec"
  - "SentrySwiftUI.podspec"
  - "Package*.swift"

  # Scripts
  - "scripts/ci-diagnostics.sh"

  # Other
  - "Makefile" # Make commands used for cross-platform setup
  - "Brewfile*" # Dependency installation affects cross-platform testing

run_lint_clang_formatting_for_prs: &run_lint_clang_formatting_for_prs
  - "**/*.h"
  - "**/*.hpp"
  - "**/*.c"
  - "**/*.cpp"
  - "**/*.m"
  - "**/*.mm"

  # GH Actions
  - ".github/workflows/lint-clang-formatting.yml"
  - ".github/file-filters.yml"

  # Formatting
  - ".clang-format"
  # Other
  - "Makefile" # Make commands used for formatting setup
  - "Brewfile*" # Tools installation affects formatting environment
  - "scripts/ci-diagnostics.sh" # CI diagnostics may affect formatting checks

run_objc_conversion_analysis_for_prs: &run_objc_conversion_analysis_for_prs
  - "SwiftConversion/**"

  # GH Actions
  - ".github/workflows/objc-conversion-analysis.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-diagnostics.sh"

run_auto_update_tools_for_prs: &run_auto_update_tools_for_prs # Auto-update tools workflow
  # Formatting
  - ".pre-commit-config.yaml"

  # GH Actions
  - ".github/workflows/auto-update-tools.yml"

  # Scripts
  - "scripts/.clang-format-version"
  - "scripts/.swiftlint-version"
  - "scripts/check-tooling-versions.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/update-tooling-versions.sh"

  # Other
  - "Brewfile*"
  - "Makefile"

run_lint_cocoapods_specs_for_prs: &run_lint_cocoapods_specs_for_prs # CocoaPods specs linting
  - "Sources/**"
  - "Tests/**"
  - "test-server/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/lint-cocoapods-specs.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "*.podspec"
  - "Gemfile.lock"

  # Other
  - "Makefile" # Make commands used for linting setup
  - "Brewfile*" # Tools installation affects linting environment
  - ".swiftlint.yml"

run_release_for_prs: &run_release_for_prs # Release-related code
  - "Sources/**"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/assemble-xcframework.sh"
  - "scripts/generate_release_matrix.sh"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # GH Actions
  - ".github/workflows/build-xcframework.yml"
  - ".github/workflows/release.yml"
  - ".github/workflows/build-xcframework-variant-slices.yml"
  - ".github/workflows/assemble-xcframework-variant.yml"
  - ".github/workflows/ui-tests-common.yml"
  - ".github/file-filters.yml"

  # Samples
  - "Samples/macOS-SPM-CommandLine/**"
  - "Samples/SPM-Dynamic/**"

run_lint_swift_formatting_for_prs: &run_lint_swift_formatting_for_prs # Swift formatting
  - "**/*.swift"

  # GH Actions
  - ".github/workflows/lint-swift-formatting.yml"
  - ".github/file-filters.yml"

  # Formatting
  - ".swiftlint.yml"

  # Other
  - "Makefile" # Make commands used for formatting setup
  - "Brewfile*" # Tools installation affects formatting environment

  # Scripts
  - "scripts/ci-diagnostics.sh"

run_lint_shellcheck_for_prs: &run_lint_shellcheck_for_prs # Shell scripts
  - "**/*.sh"

  # GH Actions
  - ".github/workflows/lint-shellcheck-formatting.yml"
  - ".github/file-filters.yml"

run_lint_dprint_for_prs: &run_lint_dprint_for_prs # dprint formatting
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.md"

  # Formatting
  - "dprint.json"

  # GH Actions
  - ".github/workflows/lint-dprint-formatting.yml"
  - ".github/file-filters.yml"

run_lint_xcode_analyze_for_prs: &run_lint_xcode_analyze_for_prs # Xcode linting
  - "Sources/**"
  - "Tests/**"
  - "test-server/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/lint-xcode-analyze.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "*.podspec"
  - "Gemfile.lock"

run_build_for_prs: &run_build_for_prs # Build-related code
  - "Sources/**"
  - "test-server/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/build.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"

  # Other
  - "fastlane/**"
  - "Gemfile.lock"
  - "Makefile" # Make commands used for CI build setup
  - "Brewfile*" # Dependency installation affects build environment
