# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  - "Sources/Sentry/SentryNSURLSessionTaskSearch.m"
  - "Sources/Sentry/SentryNetworkTracker.m"
  - "Sources/Sentry/SentryUIViewControllerSwizzling.m"
  - "Sources/Sentry/SentryNSDataSwizzling.m"
  - "Sources/Sentry/SentryNSFileManagerSwizzling.m"
  - "Sources/Sentry/SentrySubClassFinder.m"
  - "Sources/Sentry/SentryCoreDataSwizzling.m"
  - "Sources/Sentry/SentrySwizzleWrapper.m"
  - "Sources/Sentry/include/SentrySwizzle.h"
  - "Sources/Sentry/SentrySwizzle.m"
  - "Sources/Sentry/SentryFileManager.m"
  - "Sources/Sentry/SentrySerialization.m"
  - "Sources/Sentry/SentrySerialization.h"

  # GH Actions
  - ".github/workflows/changes-in-high-risk-code.yml"
  - ".github/file-filters.yml"

run_unit_tests_for_prs: &run_unit_tests_for_prs
  - "Sources/**"
  - "Tests/**"
  - "SentryTestUtils/**"
  - "SentryTestUtilsDynamic/**"
  - "SentryTestUtilsTests/**"
  - "integrations/**"

  # GH Actions
  - ".github/workflows/test.yml"
  - ".github/file-filters.yml"
  - ".github/workflows/unit-test-common.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/sentry-xcodebuild.sh"
  - "scripts/start-test-server.sh"
  - "scripts/tests-with-thread-sanitizer.sh"
  - "scripts/ci-boot-simulator.sh"
  - "scripts/ci-ensure-runtime-loaded.sh"

  # Test infrastructure
  - "test-server/**"
  - "**/*.xctestplan"
  - "Plans/**"

  # Project files
  - "Sentry.xcodeproj/**"
  - "Sentry.xcworkspace/**"
  - "Package*.swift"

  # Build configuration
  - "fastlane/**"
  - "Makefile"
  - "Brewfile*"
  - ".codecov.yml"

run_api_stability_for_prs: &run_api_stability_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/api-stability.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # Scripts
  - "scripts/build-xcframework-local.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/assemble-xcframework.sh"
  - "scripts/update-api.sh"
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # API files
  - "sdk_api.json"
  - "sdk_api_v9.json"

  # Build configuration
  - "Makefile"

run_integration_test_for_prs: &run_integration_test_for_prs
  - "Sources/**"
  - "Samples/iOS-Cocoapods-*/**"

  # GH Actions
  - ".github/workflows/integration-test.yml"
  - ".github/file-filters.yml"

  # Project files
  - "*.xcodeproj/**"
  - "*.xcworkspace/**"
  - "*.podspec"
  - "Plans/iOS-Cocoapods-Swift6_Base.xctestplan"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "fastlane/**"
  - "Gemfile.lock"

run_benchmarking_for_prs: &run_benchmarking_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/benchmarking.yml"
  - ".github/workflows/build-xcframework-variant-slices.yml"
  - ".github/workflows/assemble-xcframework-variant.yml"
  - ".github/file-filters.yml"

  # Benchmarking implementation
  - "Samples/iOS-Swift/**"
  - ".sauce/benchmarking-config.yml"
  - "Plans/iOS-Benchmarking_Base.xctestplan"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/assemble-xcframework.sh"

  # Project files
  - "Samples/iOS-Swift/iOS-Swift.yml"
  - "Samples/iOS-Swift/iOS-Swift.xcconfig"
  - "Samples/iOS-Swift/iOS-SwiftClip.xcconfig"
  - "Samples/iOS-Swift/iOS-Benchmarking.xcconfig"
  - "Package*.swift"

  # Build configuration
  - "fastlane/**"

run_test_cross_platform_for_prs: &run_test_cross_platform_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/test-cross-platform.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.podspec"
  - "SentrySwiftUI.podspec"
  - "Package*.swift"
  - "Tests/HybridSDKTest/HybridPod.podspec"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/ci-ensure-runtime-loaded.sh"

  # Build configuration
  - "Makefile"
  - "Brewfile*"

run_lint_clang_formatting_for_prs: &run_lint_clang_formatting_for_prs
  - "**/*.h"
  - "**/*.hpp"
  - "**/*.c"
  - "**/*.cpp"
  - "**/*.m"
  - "**/*.mm"

  # GH Actions
  - ".github/workflows/lint-clang-formatting.yml"
  - ".github/file-filters.yml"

  # Formatting configuration
  - ".clang-format"
  - "scripts/.clang-format-version"
  - "scripts/check-clang-format.py"

  # Scripts
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "Makefile"
  - "Brewfile*"

run_objc_conversion_analysis_for_prs: &run_objc_conversion_analysis_for_prs
  - "SwiftConversion/**"

  # GH Actions
  - ".github/workflows/objc-conversion-analysis.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "Brewfile*"

run_auto_update_tools_for_prs: &run_auto_update_tools_for_prs
  - ".github/workflows/auto-update-tools.yml"
  - ".github/file-filters.yml"

  # Tool configuration
  - ".pre-commit-config.yaml"
  - "scripts/.clang-format-version"
  - "scripts/.swiftlint-version"

  # Scripts
  - "scripts/check-tooling-versions.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/update-tooling-versions.sh"

  # Build configuration
  - "Brewfile*"
  - "Makefile"

run_lint_cocoapods_specs_for_prs: &run_lint_cocoapods_specs_for_prs
  - "Sources/**"
  - "Tests/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/lint-cocoapods-specs.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/pod-lib-lint.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "*.podspec"
  - "Tests/HybridSDKTest/HybridPod.podspec"

  # Build configuration
  - "Makefile"
  - "Brewfile*"
  - "Gemfile.lock"
  - ".swiftlint.yml"

run_release_for_prs: &run_release_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/build-xcframework.yml"
  - ".github/workflows/release.yml"
  - ".github/workflows/build-xcframework-variant-slices.yml"
  - ".github/workflows/assemble-xcframework-variant.yml"
  - ".github/workflows/ui-tests-common.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/build-xcframework-local.sh"
  - "scripts/assemble-xcframework.sh"
  - "scripts/generate_release_matrix.sh"
  - "scripts/xcframework-generated-run.sh"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # Sample projects
  - "Samples/macOS-SPM-CommandLine/**"
  - "Samples/SPM-Dynamic/**"

  # Build configuration
  - "fastlane/**"
  - "Makefile"

  # Test files
  - "Tests/Perf/metrics-test.yml"

run_lint_swift_formatting_for_prs: &run_lint_swift_formatting_for_prs
  - "**/*.swift"

  # GH Actions
  - ".github/workflows/lint-swift-formatting.yml"
  - ".github/file-filters.yml"

  # Formatting
  - ".swiftlint.yml"
  - "scripts/.swiftlint-version"

  # Scripts
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "Makefile"
  - "Brewfile*"

run_lint_shellcheck_for_prs: &run_lint_shellcheck_for_prs
  - "**/*.sh"

  # GH Actions
  - ".github/workflows/lint-shellcheck-formatting.yml"
  - ".github/file-filters.yml"

run_lint_dprint_for_prs: &run_lint_dprint_for_prs
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.md"

  # GH Actions
  - ".github/workflows/lint-dprint-formatting.yml"
  - ".github/file-filters.yml"

  # Formatting
  - "dprint.json"

run_lint_xcode_analyze_for_prs: &run_lint_xcode_analyze_for_prs
  - "Sources/**"
  - "Tests/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/lint-xcode-analyze.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "Sentry.xcworkspace/**"
  - "*.podspec"

  # Build configuration
  - "Makefile"

run_build_for_prs: &run_build_for_prs
  - "Sources/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/build.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"
  - "Package*.swift"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/sentry-xcodebuild.sh"
  - "scripts/check-uikit-linkage.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "fastlane/**"
  - "Gemfile.lock"
  - "Makefile"
  - "Brewfile*"

run_testflight_for_prs: &run_testflight_for_prs
  - ".github/workflows/testflight.yml"
  - ".github/file-filters.yml"

run_testflight_for_pushes: &run_testflight_for_pushes
  - "Sources/**"
  - "Samples/iOS-Swift/**"

  # GH Actions
  - ".github/workflows/testflight.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "fastlane/**"
  - "Makefile"

run_codeql_analysis_for_prs: &run_codeql_analysis_for_prs
  - "Sources/**"

  # GH Actions
  - ".github/workflows/codeql-analysis.yml"
  - ".github/file-filters.yml"

  # Project files
  - "Sentry.xcworkspace/**"
  - "Sentry.xcodeproj/**"

  # Scripts
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Build configuration
  - "Makefile"

run_version_bump_util_for_prs: &run_version_bump_util_for_prs
  - ".github/workflows/version-bump-util.yml"
  - ".github/file-filters.yml"

  # Version bump utilities
  - "Utils/VersionBump/**"

  # Scripts
  - "scripts/bump.sh"

  # Version-related source files
  - "Sources/Sentry/SentryMeta.m"

  # Project files with version info
  - "Sentry.podspec"
  - "SentryPrivate.podspec"
  - "SentrySwiftUI.podspec"
  - "Package*.swift"
  - "Tests/HybridSDKTest/HybridPod.podspec"

  # Configuration files
  - "Sources/Configuration/SDK.xcconfig"
  - "Sources/Configuration/Versioning.xcconfig"
  - "Sources/Configuration/SentrySwiftUI.xcconfig"

run_ui_tests_for_prs: &run_ui_tests_for_prs
  - "Sources/**"
  - "Tests/**"

  # GH Actions
  - ".github/workflows/ui-tests.yml"
  - ".github/workflows/ui-tests-cirrus-labs.yml"
  - ".github/workflows/ui-tests-common.yml"
  - ".github/workflows/build-xcframework-variant-slices.yml"
  - ".github/workflows/assemble-xcframework-variant.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/build-xcframework-slice.sh"
  - "scripts/assemble-xcframework.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/ci-ensure-runtime-loaded.sh"

  # Test plans
  - "**/*.xctestplan"
  - "Plans/**"

  # Sample projects
  - "Samples/iOS-SwiftUI/**"
  - "Samples/iOS-Swift/**"
  - "Samples/iOS-Swift6/**"
  - "Samples/SentrySampleShared/**"
  - "Samples/Shared/**"

  # Build configuration
  - "fastlane/**"
  - "Makefile"
  - "Brewfile*"

run_ui_tests_critical_for_prs: &run_ui_tests_critical_for_prs
  - "Sources/**"
  - "TestSamples/**"

  # GH Actions
  - ".github/workflows/ui-tests-critical.yml"
  - ".github/workflows/ui-tests-common.yml"
  - ".github/file-filters.yml"

  # Test plans
  - "**/*.xctestplan"
  - "Plans/**"

  # Scripts
  - "scripts/ci-boot-simulator.sh"
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"
  - "scripts/ci-ensure-runtime-loaded.sh"

  # Build configuration
  - "fastlane/**"
  - "Gemfile.lock"
  - "Makefile"
  - "Brewfile*"

run_lint_swiftlint_for_prs: &run_lint_swiftlint_for_prs
  - "Sources/**"
  - "Tests/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/lint-swiftlint-formatting.yml"
  - ".github/file-filters.yml"

  # SwiftLint configuration
  - ".swiftlint.yml"
  - "scripts/.swiftlint-version"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "*.podspec"

  # Build configuration
  - "Makefile"
  - "Brewfile*"

run_size_analysis_for_prs: &run_size_analysis_for_prs
  - "Sources/**"
  - "Samples/**"

  # GH Actions
  - ".github/workflows/size-analysis.yml"
  - ".github/file-filters.yml"

  # Scripts
  - "scripts/ci-select-xcode.sh"
  - "scripts/ci-diagnostics.sh"
  - "scripts/ci-utils.sh"

  # Project files
  - "Sentry.xcodeproj/**"
  - "*.podspec"

  # Build configuration
  - "Makefile"
  - "Brewfile*"
