# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  - 'Sources/Sentry/SentryNSURLSessionTaskSearch.m'
  - 'Sources/Sentry/SentryNetworkTracker.m'
  - 'Sources/Sentry/SentryUIViewControllerSwizzling.m'
  - 'Sources/Sentry/SentryNSDataSwizzling.m'
  - 'Sources/Sentry/SentrySubClassFinder.m'
  - 'Sources/Sentry/SentryCoreDataSwizzling.m'
  - 'Sources/Sentry/SentrySwizzleWrapper.m'
  - 'Sources/Sentry/include/SentrySwizzle.h'
  - 'Sources/Sentry/SentrySwizzle.m'

fastlane: &fastlane
  - 'fastlane/**'

sources: &sources
  - 'Sources/**'
  - 'Sentry.xcodeproj/**'

samples_all: &samples_all
  - 'Samples/**'

scripts_select_xcode: &scripts_select_xcode
  - 'scripts/ci-select-xcode.sh'

tests: &tests
  - 'Tests/**'
  - 'SentryTestUtils/**'
  - 'test-server/**'
  - '.github/workflows/test.yml'
  - 'scripts/tests-with-thread-sanitizer.sh'
  - 'scripts/xcode-test.sh'
  - '.codecov.yml'

run_unit_tests: &run_unit_tests
  - *sources
  - *tests
  - *scripts_select_xcode
  - *samples_all

run_lint: &run_lint
  - *sources
  - *tests
  - *scripts_select_xcode
  - '.github/workflows/lint.yml'
  - '*.podspec'
  - 'Gemfile.lock'

run_swift_lint: &run_swift_lint
  - '**/*.swift'
  - '.github/workflows/lint.yml'

run_format_code: &run_format_code
  - '**/*.{swift,c,h,hpp,cpp,m,mm}'
  - '.github/workflows/format-code.yml'
