minVersion: '0.9.3'
github:
  owner: getsentry
  repo: sentry-cocoa
changelogPolicy: simple
preReleaseCommand: bash ./scripts/bump.sh
statusProvider:
  name: github
targets:
  - name: github
  - name: cocoapods
    specPath: Sentry.podspec
  - name: registry
    type: sdk
    config:
      canonical: 'cocoapods:sentry-cocoa'
