minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash ./scripts/bump.sh
targets:
  - name: github
  - name: cocoapods
    id: sentry-cocoapod
    specPath: Sentry.podspec
  - name: registry
    sdks:
      cocoapods:sentry-cocoa:
  - name: gcs
    bucket: sentry-cocoa-prebuilt
    includeNames: /.*\.zip$/
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: "public, max-age=31536000"
