name: "Capture screenshot"
description: "Captures a screenshot of the machine"
inputs:
  suffix:
    description: "The suffix of the screenshot"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Capture screenshot
      shell: bash
      run: |
        screencapture -x /tmp/screenshot.png
    - name: Store screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-${{ github.job }}${{ inputs.suffix }}
        path: /tmp/screenshot.png
