platform :ios, '8.0'
use_frameworks!

target 'ObjCExample' do
  pod 'SentrySwift', :path => '../../'
  pod 'KSCrash', :git => 'git@github.com:kstenerud/KSCrash.git', :tag => '1.13.3'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    # Configure Pod targets for Xcode 8 compatibility
    config.build_settings['SWIFT_VERSION'] = '2.3'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
