#import "SentryAppStartMeasurementProvider.h"

#if SENTRY_HAS_UIKIT

#    import "PrivateSentrySDKOnly.h"
#    import "SentryAppStartMeasurement.h"
#    import "SentryInternalCDefines.h"
#    import "SentryInternalDefines.h"
#    import "SentryLogC.h"
#    import "SentrySDK+Private.h"
#    import "SentrySpanOperation.h"
#    import "SentrySwift.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * The maximum amount of seconds the app start measurement end time and the start time of the
 * transaction are allowed to be apart.
 */
static const NSTimeInterval SENTRY_APP_START_MEASUREMENT_DIFFERENCE = 5.0;

static NSObject *appStartMeasurementLock;
static BOOL appStartMeasurementRead;

@implementation SentryAppStartMeasurementProvider

+ (void)initialize
{
    if (self == [SentryAppStartMeasurementProvider class]) {
        appStartMeasurementLock = [[NSObject alloc] init];
        appStartMeasurementRead = NO;
    }
}

+ (nullable SentryAppStartMeasurement *)appStartMeasurementForOperation:(NSString *)operation
                                                         startTimestamp:
                                                             (nullable NSDate *)startTimestamp
    SENTRY_DISABLE_THREAD_SANITIZER("double-checked lock produce false alarms")
{
    // Only send app start measurement for transactions generated by auto performance
    // instrumentation.
    if (![operation isEqualToString:SentrySpanOperationUiLoad]) {
        SENTRY_LOG_DEBUG(
            @"Not returning app start measurements because it's not a ui.load operation.");
        return nil;
    }

    // Hybrid SDKs send the app start measurement themselves.
    if (PrivateSentrySDKOnly.appStartMeasurementHybridSDKMode) {
        SENTRY_LOG_DEBUG(@"Not returning app start measurements because hybrid SDK will do it in "
                         @"its own routine.");
        return nil;
    }

    // Double-Checked Locking to avoid acquiring unnecessary locks.
    if (appStartMeasurementRead == YES) {
        SENTRY_LOG_DEBUG(@"Not returning app start measurements because it was already reported.");
        return nil;
    }

    SentryAppStartMeasurement *measurement = nil;
    @synchronized(appStartMeasurementLock) {
        if (appStartMeasurementRead == YES) {
            SENTRY_LOG_DEBUG(@"Not returning app start measurements because it was already "
                             @"reported concurrently.");
            return nil;
        }

        measurement = [SentrySDKInternal getAppStartMeasurement];
        if (measurement == nil) {
            SENTRY_LOG_DEBUG(@"No app start measurement available.");
            return nil;
        }

        appStartMeasurementRead = YES;
    }

    NSDate *appStartTimestamp = measurement.appStartTimestamp;
    NSDate *appStartEndTimestamp =
        [appStartTimestamp dateByAddingTimeInterval:measurement.duration];

    NSTimeInterval difference =
        [appStartEndTimestamp timeIntervalSinceDate:SENTRY_UNWRAP_NULLABLE(NSDate, startTimestamp)];

    // Don't attach app start measurements if too much time elapsed between the end of the app start
    // sequence and the start of the transaction. This makes transactions too long.
    if (difference > SENTRY_APP_START_MEASUREMENT_DIFFERENCE
        || difference < -SENTRY_APP_START_MEASUREMENT_DIFFERENCE) {
        SENTRY_LOG_DEBUG(@"Not returning app start measurements because too much time elapsed.");
        return nil;
    }

    SENTRY_LOG_DEBUG(@"Returning app start measurement.");
    return measurement;
}

+ (void)reset
{
    @synchronized(appStartMeasurementLock) {
        appStartMeasurementRead = NO;
    }
}

@end

NS_ASSUME_NONNULL_END

#endif // SENTRY_HAS_UIKIT
