parent_config: ../.swiftlint.yml

disabled_rules:
  - todo
  - object_literal
  - line_length
  - file_length
  - cyclomatic_complexity
  - switch_case_on_newline
  - type_body_length
  - function_body_length
  - identifier_name
