name: Upload to Testflight
on:
  push:
    branches:
      - master
    paths:
      - 'Sources/**'
      - 'Samples/iOS-Swift/**'
      - '.github/workflows/testflight.yml'

jobs:

  upload_to_testflight:
    name: Build and Upload iOS-Swift to Testflight
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/ci-select-xcode.sh
      - uses: ruby/setup-ruby@v1

      - name: Install SentryCli
        run: brew install getsentry/tools/sentry-cli

      - name: Setup fastlane
        run: bundle install   

      # We upload a new version to TestFlight on every commit on Master
      # So we need to bump the bundle version each time
      - name: Bump Bundle Version
        env: 
          FASTLANE_BUNDLE_VERSION: ${{ github.run_number }}
        run: bundle exec fastlane bump_bundle_version
        shell: sh

      - name: Remove preview version suffixes
        run: bundle exec fastlane remove_preview_version_suffixes
        shell: sh

      - name: Run Fastlane
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          FASTLANE_BUNDLE_VERSION: ${{ github.run_number }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          bundle exec fastlane build_ios_swift
          bundle exec fastlane ios_swift_to_testflight
        shell: sh

      - name: Archiving
        uses: actions/upload-artifact@v2
        with:
          name: dSYMs 
          path: |
            ${{ github.workspace }}/iOS-Swift.*
            ${{ github.workspace }}/*.dSYM.zip
            ${{ github.workspace }}/dSYMs/

