name: "Common UI Test Steps"
description: "Common steps for UI tests including setup, permissions, and artifact handling"
inputs:
  fastlane_command:
    description: "The fastlane command to run"
    required: true
  xcresult_name:
    description: "Name for the xcresult artifact"
    required: true
  raw_output_name:
    description: "Name for the raw output artifact"
    required: true
  xcode_version:
    description: "Xcode version"
    required: true
  build_with_make:
    description: "Build with make"
    required: false
    default: "false"
  build_with_script:
    description: "Build with script"
    required: false
    default: "true"
  build_script_parameters:
    description: "Parameters for the build script"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Print hardware info
      shell: bash
      run: system_profiler SPHardwareDataType

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: ./scripts/ci-select-xcode.sh ${{ inputs.xcode_version }}
      shell: sh

    - run: make init-ci-build
      shell: sh
      if: ${{ inputs.build_with_make == 'true' }}

    - run: make xcode
      shell: sh
      if: ${{ inputs.build_with_make == 'true' }}

    - run: ./scripts/build-xcframework.sh ${{ inputs.build_script_parameters }}
      shell: sh
      if: ${{ inputs.build_with_script == 'true' }}

    - name: Add Microphone permissions
      uses: ./.github/actions/add-microphone-permissions

    - name: Run Fastlane
      shell: sh
      run: bundle exec fastlane ${{ inputs.fastlane_command }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@65fe03598d8d251738592a497a9e8547a5c48eaa # v5.6.0
      if: always()
      with:
        report_paths: "build/reports/junit.xml"
        fail_on_failure: true
        fail_on_parse_error: true
        detailed_summary: true

    - name: Upload Result Bundle
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ inputs.xcresult_name }}
        path: fastlane/test_results/${{ inputs.xcresult_name }}.xcresult

    - name: Archiving Raw Test Logs
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: ${{ inputs.raw_output_name }}
        path: |
          ~/Library/Logs/scan/*.log
          ./fastlane/test_output/**

    - name: Store screenshot
      uses: ./.github/actions/capture-screenshot
      if: failure()
