// Test-only declarations formerly supplied by the Xcode bridging header.
#pragma once
#import "SentryTestsBridge.h"

#import "SentryDefines.h"
#import "SentryGeo+Private.h"

#import "../../../SentryTestUtils/Headers/SentryLaunchProfiling+Tests.h"

#if SENTRY_HAS_UIKIT
#    import "../../SentryTests/MockUIScene.h"
#    import "SentryDefaultUIViewControllerPerformanceTracker.h"
#endif // SENTRY_HAS_UIKIT

#if SENTRY_TARGET_PROFILING_SUPPORTED
#    import "../../../Sources/Sentry/Profiling/SentryProfilerSerialization+Test.h"
#    import "../../SentryTests/SentryContinuousProfiler+Test.h"
#    import "../../SentryTests/SentryTraceProfiler+Test.h"
#    import "SentryContinuousProfiler.h"
#    import "SentryMetricProfiler.h"
#    import "SentryProfiler+Private.h"
#    import "SentryProfilerDefines.h"
#    import "SentryProfilerMocksSwiftCompatible.h"
#    import "SentryProfilerSerialization.h"
#    import "SentryProfilerState.h"
#    import "SentryProfilerTestHelpers.h"
#endif // SENTRY_TARGET_PROFILING_SUPPORTED

@import _SentryPrivate;

#import "../../SentryTests/Helper/ExceptionCatcher.h"
#import "../../SentryTests/Networking/NSData+Unzip.h"
#import "NSMutableDictionary+Sentry.h"
#if !SDK_V10
#    import "SentryANRTrackerV1.h"
#    import "SentryANRTrackerV2.h"
#endif
#import "../../../SentryTestUtils/Headers/SentryFileManager+Test.h"
#import "../../../SentryTestUtils/Headers/SentryHub+Test.h"
#import "../../../Sources/SentryCrash/Recording/Monitors/SentryCrashMonitorContext.h"
#import "../../../Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.h"
#import "../../../Sources/SentryCrash/Recording/SentryCrashCachedData.h"
#import "../../../Sources/SentryCrash/Recording/SentryCrashDoctor.h"
#import "../../../Sources/SentryCrash/Recording/SentryCrashReport.h"
#import "../../../Sources/SentryCrash/Recording/SentryCrashReportStore.h"
#import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashCxaThrowSwapper.h"
#import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.h"
#import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_Backtrace.h"
#import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.h"
#import "../../SentryTests/Categories/SentrySanitizerUtils+Tests.h"
#import "../../SentryTests/Helper/SentryLogTestHelper.h"
#import "../../SentryTests/Helper/SentryTestObjCRuntimeWrapper.h"
#import "../../SentryTests/Integrations/Performance/Network/URLSessionTaskMock.h"
#import "../../SentryTests/Integrations/Performance/SentryInitializeForGettingSubclassesNotCalled.h"
#import "../../SentryTests/Integrations/Performance/SentryPerformanceTracker+Testing.h"
#import "../../SentryTests/Integrations/SentryCrash/SentryCrashScopeHelper.h"
#import "../../SentryTests/SentryClient+TestInit.h"
#import "../../SentryTests/SentryCrash/SentryCrash+Test.h"
#import "../../SentryTests/SentryCrash/SentryCrashBinaryImageCache+Test.h"
#import "../../SentryTests/SentryCrash/SentryCrashBinaryImageCacheTestHelper.h"
#import "../../SentryTests/SentrySDKInternal+Tests.h"
#import "../../SentryTests/TestUtils/SentryBooleanSerialization.h"
#import "../../SentryTests/TestUtils/SentryClassRegistrator.h"
#import "../../SentryTests/TestUtils/SentryInvalidJSONString.h"
#import "../../SentryTests/Transaction/SentryTracer+Test.h"
#import "../../SentryTests/Transaction/TestSentrySpan.h"
#import "SentryAppStartMeasurement+Private.h"
#import "SentryAppStartMeasurementProvider.h"
#import "SentryAttachment+Private.h"
#import "SentryBreadcrumb+Private.h"
#import "SentryBuildAppStartSpans.h"
#import "SentryClient+Private.h"
#import "SentryClient.h"
#import "SentryCrashBinaryImageCache.h"
#import "SentryCrashC.h"
#import "SentryCrashDebug.h"
#import "SentryCrashDefaultMachineContextWrapper.h"
#import "SentryCrashInstallation+Private.h"
#import "SentryCrashMachineContext.h"
#import "SentryCrashMachineContext_Apple.h"
#import "SentryCrashMonitor.h"
#import "SentryCrashMonitor_AppState.h"
#import "SentryCrashMonitor_System.h"
#import "SentryCrashReportSink.h"
#import "SentryCrashScopeObserver.h"
#import "SentryCrashStackEntryMapper.h"
#import "SentryCrashUUIDConversion.h"
#import "SentryDateUtils.h"
#import "SentryDebugMeta.h"
#import "SentryDefaultThreadInspector.h"
#import "SentryDefaultUIViewControllerPerformanceTracker.h"
#import "SentryEnvelopeRateLimit.h"
#import "SentryEvent+Private.h"
#import "SentryFileIOTrackerHelper.h"
#import "SentryFileManagerHelper.h"
#import "SentryFormatter.h"
#import "SentryFrame.h"
#import "SentryHttpStatusCodeRange+Private.h"
#import "SentryHub+Private.h"
#import "SentryInternalNotificationNames.h"
#import "SentryLogC.h"
#import "SentryMechanism.h"
#import "SentryMechanismContext.h"
#import "SentryNSDataUtils.h"
#import "SentryNSError.h"
#import "SentryNSURLSessionTaskSearch.h"
#import "SentryNoOpSpan.h"
#import "SentryPerformanceTracker.h"
#import "SentryProfilingConditionals.h"
#import "SentrySDK+Private.h"
#import "SentrySampleDecision+Private.h"
#import "SentrySanitizerUtils.h"
#import "SentryScope+Private.h"
#import "SentryScopeSyncC.h"
#import "SentrySerialization.h"
#import "SentrySessionReplaySyncC.h"
#import "SentrySpanDataKey.h"
#import "SentrySpanId.h"
#import "SentrySpanInternal.h"
#import "SentrySpanOperation.h"
#import "SentryStacktrace.h"
#import "SentryStacktraceBuilder.h"
#import "SentryThread.h"
#import "SentryTime.h"
#import "SentryTraceOrigin.h"
#import "SentryTracePropagation.h"
#import "SentryTracer+Private.h"
#import "SentryTracer.h"
#import "SentryTransaction+Private.h"
#import "SentryTransaction.h"
#import "SentryTransactionContext+Private.h"
#import "SentryTransportFactory.h"
#import "SentryUncaughtNSExceptions.h"
#import "SentryWeakMap.h"
