// Import-only entry point shared by Xcode and SwiftPM. Keep generated Swift interfaces out.
// SDK declarations retain their original implementations and owning module identities.
@import _SentryPrivate;
#import "../../../Sources/Sentry/SentryAsyncSafeLog.h"
#import "../../../Sources/Sentry/SentryFileIO.h"
#import "../../../Sources/Sentry/SentryJSONStreamWriter.h"
#import "../../../Sources/Sentry/include/NSMutableDictionary+Sentry.h"
#import "../../../Sources/Sentry/include/SentryCrashStackEntryMapper.h"
#import "../../../Sources/Sentry/include/SentryFormatter.h"
#import "../../../Sources/Sentry/include/SentryGeo+Private.h"
#import "../../../Sources/Sentry/include/SentryHttpStatusCodeRange+Private.h"
#import "../../../Sources/Sentry/include/SentryInternalNotificationNames.h"
#import "../../../Sources/Sentry/include/SentrySampleDecision+Private.h"
#import "../../../Sources/Sentry/include/SentryTracer+Private.h"
#import "../../../Sources/Sentry/include/SentryTransportFactory.h"
#import "../../../Sources/Sentry/include/SentryWeakMap.h"
#import "SentryProfilingConditionals.h"
#if !SDK_V10
#    import "../../../Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.h"
#    import "../../../Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException.h"
#    import "../../../Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException_StackCursor.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashBinaryImageCacheState.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashCachedData.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashDoctor.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashReport.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashReportFixer.h"
#    import "../../../Sources/SentryCrash/Recording/SentryCrashReportStore.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashCPU.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashCxaThrowSwapper.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashDate.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashDynamicLinker+Test.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodec.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashMach-O.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashMach.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashMemory.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashNSErrorUtil.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashObjC.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashSignalInfo.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_Backtrace.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_MachineContext.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashString.h"
#    import "../../../Sources/SentryCrash/Recording/Tools/SentryCrashSysCtl.h"
#    import "../../../Sources/SentryCrash/Reporting/Filters/SentryCrashReportFilterBasic.h"
#    import "../../../Sources/SentryCrash/Reporting/Filters/Tools/SentryDictionaryDeepSearch.h"
#endif

#if SENTRY_TARGET_PROFILING_SUPPORTED
#    import "SentryMetricProfiler.h"
#    import "SentryProfilerSerialization+Test.h"
#    import "SentryProfilerSerialization.h"
#    import "SentryProfilerState.h"
#    import "SentryProfilerTestHelpers.h"
#endif

// Wrappers mirror SDK headers; Utils contains all testing behavior.
#import "Utils/ExceptionCatcher.h"
#import "Utils/MockUIScene.h"
#import "Utils/NSData+Unzip.h"
#import "Utils/SentryBooleanSerialization.h"
#import "Utils/SentryCrashBinaryImageCacheTestHelper.h"
#import "Utils/SentryCrashScopeHelper.h"
#import "Utils/SentryInitializeForGettingSubclassesNotCalled.h"
#import "Utils/SentryInvalidJSONString.h"
#import "Utils/SentryLogTestHelper.h"
#import "Utils/SentrySanitizerUtils+Tests.h"
#import "Utils/SentryTestObjCRuntimeWrapper.h"
#import "Utils/SentryTestState.h"
#import "Utils/TestSentrySpan.h"
#import "Utils/URLSessionTaskMock.h"
#import "Wrappers/SentryClient+PrivateWrapper.h"
#import "Wrappers/SentryClientWrapper.h"
#import "Wrappers/SentryContinuousProfilerWrapper.h"
#import "Wrappers/SentryCrashBinaryImageCacheWrapper.h"
#import "Wrappers/SentryDelayedFramesTrackerWrapper.h"
#import "Wrappers/SentryEnvelopeRateLimitWrapper.h"
#import "Wrappers/SentryFileManagerHelperWrapper.h"
#import "Wrappers/SentryHttpTransportWrapper.h"
#import "Wrappers/SentryHub+PrivateWrapper.h"
#import "Wrappers/SentryHubWrapper.h"
#import "Wrappers/SentryLaunchProfilingWrapper.h"
#import "Wrappers/SentryPerformanceTrackerWrapper.h"
#import "Wrappers/SentryProfiler+PrivateWrapper.h"
#import "Wrappers/SentrySDKInternalWrapper.h"
#import "Wrappers/SentryScope+PrivateWrapper.h"
#import "Wrappers/SentrySpanInternal+PrivateWrapper.h"
#import "Wrappers/SentryTraceContext+PrivateWrapper.h"
#import "Wrappers/SentryTraceProfilerWrapper.h"
#import "Wrappers/SentryTracer+PrivateWrapper.h"
#import "Wrappers/SentryTracerWrapper.h"
#import "Wrappers/SentryTransactionContext+PrivateWrapper.h"
