# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWatchOSExample' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
end

target 'SwiftWatchOSExample WatchKit Extension' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
end
