# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWatchOSExample' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
  pod 'KSCrash', :git => 'git@github.com:kstenerud/KSCrash.git', :tag => '1.11.2'
end

target 'SwiftWatchOSExample WatchKit Extension' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
  pod 'KSCrash', :git => 'git@github.com:kstenerud/KSCrash.git', :tag => '1.11.2'
end
