// This import must be first. In SPM the file needs to be in the "include" directory since that is
// the Public headers directory, but in Cocoapods it must be in HybridPublic because it is used in
// that public interface too. In order to handle both these cases the file is in HybridPublic but
// symlinked to include.
#import "SentryProfilingConditionals.h"

// Sentry internal headers that are needed for swift code; you cannot import headers that depend on
// public interfaces here
#import "NSLocale+Sentry.h"
#import "SentryANRStoppedResultInternal.h"
#import "SentryANRTrackerInternalDelegate.h"
#import "SentryBinaryImageCacheCallbacks.h"
#import "SentryClient+Private.h"
#import "SentryConcurrentRateLimitsDictionary.h"
#import "SentryCrashAsync.h"
#import "SentryCrashBinaryImageCache.h"
#import "SentryCrashDynamicLinker.h"
#import "SentryCrashExceptionApplicationHelper.h"
#import "SentryCrashUUIDConversion.h"
#import "SentryDataCategoryMapper.h"
#import "SentryDiscardReasonMapper.h"
#import "SentryDsn+Private.h"
#import "SentryEnvelopeAttachmentHeader.h"
#import "SentryEventSwiftHelper.h"
#import "SentryHub+Private.h"
#import "SentryIntegrationProtocol.h"
#import "SentryNSDataUtils.h"
#import "SentrySDK+Private.h"
#import "SentryTime.h"
#import "SentryUserAccess.h"
#import "SentryViewHierarchyProviderHelper.h"
#import "_SentryDispatchQueueWrapperInternal.h"

// Headers that also import SentryDefines should be at the end of this list
// otherwise it wont compile
#import "SentryANRTrackerV1.h"
#import "SentryANRTrackerV2.h"
#import "SentryAsyncLog.h"
#import "SentryContinuousProfiler.h"
#import "SentryCrash.h"
#import "SentryCrashDebug.h"
#import "SentryCrashMonitor_AppState.h"
#import "SentryCrashMonitor_System.h"
#import "SentryDateUtils.h"
#import "SentryDebugImageProviderInternal.h"
#import "SentryDefaultAppStateManager.h"
#import "SentryDefaultThreadInspector.h"
#import "SentryDefaultUIViewControllerPerformanceTracker.h"
#import "SentryDelayedFramesTracker.h"
#import "SentryDependencyContainerSwiftHelper.h"
#import "SentryDeviceContextKeys.h"
#import "SentryFileIOTrackerHelper.h"
#import "SentryFileManagerHelper.h"
#import "SentryInstallation.h"
#import "SentryMeta.h"
#import "SentryMsgPackSerializer.h"
#import "SentryNSDictionarySanitize.h"
#import "SentryPerformanceTracker.h"
#import "SentryProfiler+Private.h"
#import "SentrySDKInternal.h"
#import "SentryScope+PrivateSwift.h"
#import "SentryScope.h"
#import "SentrySerialization.h"
#import "SentrySessionInternal.h"
#import "SentrySpanDataKey.h"
#import "SentrySpanOperation.h"
#import "SentrySwizzleWrapperHelper.h"
#import "SentrySysctlObjC.h"
#import "SentryTraceContext+Private.h"
#import "SentryTraceHeader.h"
#import "SentryTraceOrigin.h"
#import "SentryTraceProfiler.h"
#import "SentryWatchdogTerminationBreadcrumbProcessor.h"
