@startuml

interface SpanProtocol

class UIViewControllerPerformanceTracker
class PerformanceTracker
class Span {
    timestamp
}
class Tracer

Span --|> SpanProtocol
Tracer --|> SpanProtocol

UIViewControllerPerformanceTracker *-- PerformanceTracker
PerformanceTracker "1" *-- "many" SpanProtocol 
Tracer "1" *-- "many" SpanProtocol
Tracer "observers" --  Span::timestamp

@enduml
