#!/bin/bash
set -euo pipefail

NEW_CHECKSUM=$(shasum -a 256 Carthage/Sentry.xcframework.zip | awk '{print $1}')

pwd

sed -i '' "s/checksum: \".*\" \/\/generated by \".*\"/checksum: \"$NEW_CHECKSUM\" \/\/generated by \"$GITHUB_RUN_ID\"/" "Package.swift"

#echo "Updating Package.swift framework SHA"
#git config --global user.email "bot+github-bot@sentry.io"
#git config --global user.name "Sentry Github Bot"
#git add .
#git commit -m "Update Package.swift framework SHA"
#git push origin $GITHUB_BRANCH
