#!/bin/bash
set -euo pipefail

GITHUB_BRANCH="${1}"
NEW_CHECKSUM=$(shasum -a 256 ${2} | awk '{print $1}')

sed -i '' "s/checksum: \".*\" \/\/generated by \".*\"/checksum: \"$NEW_CHECKSUM\" \/\/generated by \"${3}\"/" "Package.swift"

echo "Updating Package.swift framework SHA"
git config --global user.email "bot+github-bot@sentry.io"
git config --global user.name "Sentry Github Bot"
git add .
git commit -m "Update Package.swift framework SHA"
git push origin $GITHUB_BRANCH
