#!/bin/bash
set -euo pipefail

NEW_CHECKSUM=$(shasum -a 256 Carthage/Sentry.xcframework.zip | awk '{print $1}')

sed -i "s/checksum: \".*\" \/\/generated by \".*\"/checksum: \"$NEW_CHECKSUM\" \/\/generated by \"$GITHUB_RUN_ID\"/" Package.swift
