# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MacExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
  pod 'KSCrash', :git => 'git@github.com:kstenerud/KSCrash.git', :tag => '1.13.4'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    # Configure Pod targets for Xcode 8 compatibility
    config.build_settings['SWIFT_VERSION'] = '2.3'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
