#import <Foundation/Foundation.h>

#import "SentryObjCDefines.h"

// Re-declared ObjC types (standalone headers, no transitive imports from Sentry)
#import "SentryObjCAppStartMeasurement.h"
#import "SentryObjCAttachment.h"
#import "SentryObjCBaggage.h"
#import "SentryObjCBreadcrumb.h"
#import "SentryObjCDebugMeta.h"
#import "SentryObjCError.h"
#import "SentryObjCEvent.h"
#import "SentryObjCException.h"
#import "SentryObjCFrame.h"
#import "SentryObjCGeo.h"
#import "SentryObjCHttpStatusCodeRange.h"
#import "SentryObjCId.h"
#import "SentryObjCLevel.h"
#import "SentryObjCMeasurementUnit.h"
#import "SentryObjCMechanism.h"
#import "SentryObjCMechanismContext.h"
#import "SentryObjCMessage.h"
#import "SentryObjCNSError.h"
#import "SentryObjCReplayApi.h"
#import "SentryObjCRequest.h"
#import "SentryObjCSampleDecision.h"
#import "SentryObjCSamplingContext.h"
#import "SentryObjCScope.h"
#import "SentryObjCSerializable.h"
#import "SentryObjCSpanContext.h"
#import "SentryObjCSpanId.h"
#import "SentryObjCSpanProtocol.h"
#import "SentryObjCSpanStatus.h"
#import "SentryObjCStacktrace.h"
#import "SentryObjCThread.h"
#import "SentryObjCTraceContext.h"
#import "SentryObjCTraceHeader.h"
#import "SentryObjCTransactionContext.h"
#import "SentryObjCTransactionNameSource.h"
#import "SentryObjCUser.h"

// Swift @objc types
#import "SentryObjCLogger.h"
#import "SentryObjCOptions.h"
#import "SentryObjCReplayOptions.h"
#import "SentryObjCSDK.h"

// Wrappers for Swift-only types
#import "SentryObjCAttributeContent.h"
#import "SentryObjCMetric.h"
#import "SentryObjCMetricValue.h"
#import "SentryObjCRedactRegionType.h"
#import "SentryObjCUnit.h"
