platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'App' do
  pod 'Sentry', :path => "../../"
end

target 'TestKeyboardExtension' do
  pod 'Sentry', :path => "../../"
end
