name: "Prepare Package.swift"
description: "Prepares Package.swift"
inputs:
  is-pr:
    description: "Whether the build is a PR"
    required: true
    default: "false"
  remove-duplicate:
    description: "Whether to remove targets that produce duplicate files. These targets cause SPM validation errors."
    default: "false"
  change-path:
    description: "Whether to change the path of the framework"
    default: "true"
  package-file:
    description: "The package file to prepare"
    required: true
    default: "Package.swift"
runs:
  using: "composite"
  steps:
    - name: Remove Sentry-Dynamic-WithARM64e target
      # We don't build it on PRs, so we need to remove it from the package.swift file.
      if: ${{ inputs.is-pr == 'true' }}
      shell: bash
      env:
        PACKAGE_FILE: ${{ inputs.package-file }}
      run: |
        sed -i '' '/Sentry-Dynamic-WithARM64e/d' $PACKAGE_FILE
        sed -i '' '/Sentry-WithoutUIKitOrAppKit-WithARM64e/d' $PACKAGE_FILE
        sed -i '' '/^[[:space:]]*\.binaryTarget($/{N;/\n[[:space:]]*),\{0,1\}$/d;}' $PACKAGE_FILE
    - name: Remove duplicate target
      if: ${{ inputs.remove-duplicate == 'true' }}
      shell: bash
      env:
        PACKAGE_FILE: ${{ inputs.package-file }}
      run: |
        sed -i '' '/Sentry-Dynamic/d' $PACKAGE_FILE
        sed -i '' '/Sentry-WithoutUIKitOrAppKit/d' $PACKAGE_FILE
        sed -i '' '/^[[:space:]]*\.binaryTarget($/{N;/\n[[:space:]]*),\{0,1\}$/d;}' $PACKAGE_FILE
    - name: Change path of the framework
      if: ${{ inputs.change-path == 'true' }}
      shell: bash
      env:
        PACKAGE_FILE: ${{ inputs.package-file }}
      run: |
        sed -i '' 's/url.*//g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Static/path: "Sentry.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Dynamic-WithARM64e/path: "Sentry-Dynamic-WithARM64e.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Dynamic/path: "Sentry-Dynamic.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-WithoutUIKitOrAppKit-WithARM64e/path: "Sentry-WithoutUIKitOrAppKit-WithARM64e.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-WithoutUIKitOrAppKit/path: "Sentry-WithoutUIKitOrAppKit.xcframework.zip"/g' $PACKAGE_FILE
