name: "Prepare Package.swift"
description: "Prepares Package.swift"
inputs:
  is-pr:
    description: "Whether the build is a PR"
    required: true
    default: "false"
  package-file:
    description: "The package file to prepare"
    required: true
    default: "Package.swift"
runs:
  using: "composite"
  steps:
    - name: Remove newer package files
      # Remove newer package files when processing Package.swift to prevent interference
      if: ${{ inputs.package-file == 'Package.swift' }}
      shell: bash
      run: rm -rf Package@swift*
    - name: Remove Sentry-Dynamic-WithARM64e target
      # We don't build it on PRs, so we need to remove it from the package.swift file.
      if: ${{ inputs.is-pr == 'true' }}
      shell: bash
      env:
        PACKAGE_FILE: ${{ inputs.package-file }}
      run: |
        sed -i '' '/Sentry-Dynamic-WithARM64e/d' $PACKAGE_FILE
        sed -i '' '/^[[:space:]]*\.binaryTarget($/{N;/\n[[:space:]]*),$/d;}' $PACKAGE_FILE
    - name: Change path of the framework
      shell: bash
      env:
        PACKAGE_FILE: ${{ inputs.package-file }}
      run: |
        sed -i '' 's/url.*//g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Static/path: "Sentry.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Dynamic-WithARM64e/path: "Sentry-Dynamic-WithARM64e.xcframework.zip"/g' $PACKAGE_FILE
        sed -i '' 's/checksum: ".*" \/\/Sentry-Dynamic/path: "Sentry-Dynamic.xcframework.zip"/g' $PACKAGE_FILE
