# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTVOSExample' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
  pod 'KSCrash', :git => 'git@github.com:kstenerud/KSCrash.git', :tag => '1.13.4'
end
