# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTVOSExample' do
  use_frameworks!
  pod 'SentrySwift', :path => '../../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    # Configure Pod targets for Xcode 8 compatibility
    config.build_settings['SWIFT_VERSION'] = '2.3'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
