# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTVOSExample' do
  use_frameworks!
  pod 'KSCrash', :path => '../../../../KSCrash'
  pod 'SentrySwift', :path => '../../'

end
