name: Changelog Preview
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@667b5f5669552a35990a11ff6ac1131febb07446 # v2
    secrets: inherit
