name: Check Code Formatting
on:
  push:
    branches:
      - main
    paths:
      - "Sources/**"
      - "Tests/**"
      - "test-server/**"
      - "Samples/**"
      - ".github/workflows/check-code-formatting.yml"
      
  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "test-server/**"
      - "Samples/**"
      - ".github/workflows/check-code-formatting.yml"

jobs:
  format-code:
    name: Format Code
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: make init-ci-format

      - name: Format Code
        run: make format

      - name: Fail Formatting Changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ Some code is not formatted correctly. Please run 'make format' and commit the changes."
            git status
            git diff
            exit 1
          else
            echo "✅ All code is formatted correctly."
          fi
