name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  danger:
    name: Danger
    uses: getsentry/github-workflows/.github/workflows/danger.yml@v2
