# Defines a workflow that generates large volumes of real-ish data to work with for various development tasks.

name: Generate Test Data
on:
  schedule:
    - cron: '0 7 * * *' # every day at 0700 UTC (midnight SF, 0300 NYC, 0900 Paris)
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/data-generator.yml'

jobs:
  build-data-generator-targets:
    name: Build UITest Targets
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/ci-select-xcode.sh 13.4.1
      - run: git apply ./scripts/set-device-tests-environment.patch
      - run: fastlane build_data_generator_ui_test
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      - name: Archiving DerivedData
        uses: actions/upload-artifact@v3
        with:
          name: data-generator-build-products
          path: |
            **/Debug-iphoneos/TrendingMovies.app
            **/Debug-iphoneos/DataGeneratorUITests-Runner.app

  run-data-generator:
    runs-on: ubuntu-latest
    needs: build-data-generator-targets
    strategy:
      fail-fast: false
      matrix:
        iOS: [15.5,  15.4,  14.8,  14.7,  13.7,  13.6.1,  13.5.1,  12.5.5,  12.5.4,  12.5.3,  12.4.8, 12.4.1 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: data-generator-build-products
      - run: npm install -g saucectl@0.99.4
      - name: Run Tests in SauceLab
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: saucectl run --select-suite iOS-${{ matrix.iOS }}
