name: Integration Tests
on:
  push:
    branches:
      - master
      - ci/**

jobs:

  test:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['13.2']
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'home-assistant/iOS'
          ref: '6d6606aed63a778c5a2bd64f8981823433a7f2fa'
      
      # Use github.event.pull_request.head.sha instead of github.sha when available as 
      # the github.sha is be the pre merge commit id for PRs.
      # See https://github.community/t/github-sha-isnt-the-value-expected/17903/17906.
      - name: Set Sentry Pod to current git commit
        run: >-
          if [[ "${{ github.event.pull_request.head.sha }}" != "" ]]; then
            ESCAPED_REPLACE=$(printf '%q\n' "pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :commit => '${{ github.event.pull_request.head.sha }}'")
            sed -i '' 'pod \'Sentry\'/$ESCAPED_REPLACE/g' Podfile
          else
            ESCAPED_REPLACE=$(printf '%q\n' "pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :commit => '${{ github.sha }}'")
            sed -i '' 'pod \'Sentry\'/$ESCAPED_REPLACE/g' Podfile
          fi  
        shell: bash

      - uses: actions/cache@v2
        name: "Cache: Pods"
        id: cache_pods
        with:
          path: |
            Pods
            Tools/MaterialDesignIcons.ttf
            Tools/MaterialDesignIcons.json
          key: >-
            ${{ runner.os }}-pods-${{ matrix.xcode }}-
            ${{ hashFiles('**/Gemfile.lock', '**/Podfile.lock', 'Tools/BuildMaterialDesignIconsFont.sh') }}

      - uses: actions/cache@v2
        name: "Cache: Gems"
        id: cache_gems
        with:
          path: vendor/bundle
          key: >-
            ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ env.DEVELOPER_DIR }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Brews
        # right now, we don't need anything from brew for tests, so save some time
        if: ${{ false }}
        run: brew bundle

      - name: Install Gems
        if: steps.cache_gems.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3

      - name: Install Pods Release
        if: steps.cache_pods.outputs.cache-hit != 'true'
        run: bundle exec pod install --repo-update

      - name: Run tests
        run: bundle exec fastlane test
