name: Integration Tests
on:
  push:
    branches:
      - master
      - ci/**

jobs:

  # We borrow the tests of Home Assistant under the MIT license: https://github.com/home-assistant/iOSe.
  # The following steps checkout Home Assistant and apply a github patch to the project. The patch adds
  # Sentry to the tests with auto performance monitoring enabled. While the tests are running a 
  # transaction is bound to the scope, so the Sentry SDK adds spans to the transaction. This doesn't
  # validate if the Sentry SDK adds proper spans.
  home-assistant-tests:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['13.2']
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'home-assistant/iOS'
          ref: '6d6606aed63a778c5a2bd64f8981823433a7f2fa'
      
      # Use github.event.pull_request.head.sha instead of github.sha when available as 
      # the github.sha is the pre merge commit id for PRs.
      # See https://github.community/t/github-sha-isnt-the-value-expected/17903/17906.
      - name: Download Patch
        run: >-
          if [[ "${{ github.event.pull_request.head.sha }}" != "" ]]; then
            curl https://raw.githubusercontent.com/getsentry/sentry-cocoa/${{ github.event.pull_request.head.sha }}/scripts/add-sentry-to-homekit.patch --output sentry.patch
          else
            curl https://raw.githubusercontent.com/getsentry/sentry-cocoa/${{ github.sha  }}/scripts/add-sentry-to-homekit.patch --output sentry.patch
          fi  
        shell: bash

      - name: Set SPM revision to current git commit
        run: >-
          if [[ "${{ github.event.pull_request.head.sha }}" != "" ]]; then
            sed -i '' 's/__GITHUB_REVISION_PLACEHOLDER__/${{ github.event.pull_request.head.sha }}/g' sentry.patch 
          else
            sed -i '' 's/__GITHUB_REVISION_PLACEHOLDER__/${{ github.sha }}/g' sentry.patch 
          fi  
        shell: bash
      
      - run: git apply sentry.patch  

      - uses: actions/cache@v2
        name: "Cache: Pods"
        id: cache_pods
        with:
          path: |
            Pods
            Tools/MaterialDesignIcons.ttf
            Tools/MaterialDesignIcons.json
          key: >-
            ${{ runner.os }}-pods-${{ matrix.xcode }}-
            ${{ hashFiles('**/Gemfile.lock', '**/Podfile.lock', 'Tools/BuildMaterialDesignIconsFont.sh') }}

      - uses: actions/cache@v2
        name: "Cache: Gems"
        id: cache_gems
        with:
          path: vendor/bundle
          key: >-
            ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ env.DEVELOPER_DIR }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Install Pods Release
        run: bundle exec pod install --repo-update

      - name: Run tests
        run: bundle exec fastlane test
