# We want to run dprint for only the files it checks without running the other linters, which are
# expensive. For example, dprint should run for markdown changes, but pod lib lint doesn't need to
# run for markdown changes. Therefore, we run it in an extra workflow.

name: lint-dprint
on:
  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.json"
      - "**/*.md"

  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.json"
      - "**/*.md"

jobs:
  lint-dprint:
    name: Run dprint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
