name: Performance Benchmarks
on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/performance-benchmarks.yml'

jobs:
  benchmark-with-movies:
    runs-on: macos-11
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Benchmark Sentry SDK PR
        run: make benchmark-sentry-pr
