name: Runner
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  macos:
    name: "Run on the fastest infrastructure"
    runs-on: [
      "ghcr.io/cirruslabs/macos-runner:tahoe",
      "runner_group_id:10",
    ]
    steps:
      - uses: actions/checkout@v4
      - name: Print macOS version
        run: |
          echo "group_id: 10"
          echo "OS version:"
          sw_vers
      - name: List Installed Xcodes
        run: xcodes installed
      - name: List Installed iOS SDKs
        run: xcrun simctl list
