name: Runner
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  macos:
    strategy:
      matrix:
        group_id:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
    name: "Run on the fastest infrastructure"
    runs-on: [
      "ghcr.io/cirruslabs/macos-runner:tahoe",
      "runner_group_id:${{ matrix.group_id }}",
    ]
    steps:
      - uses: actions/checkout@v4
      - name: Print macOS version
        run: |
          echo "group_id: ${{ matrix.group_id }}"
          echo "OS version:"
          sw_vers
      - name: List Installed Xcodes
        run: xcodes installed
      - name: List Installed iOS SDKs
        run: xcrun simctl list
