name: validate libs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate-podspec:
    name: Validate Podspec
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Podspec
        run: pod lib lint
        shell: sh

  validate-carthage:
    name: Validate Carthage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build-carthage
        shell: sh  
