name: validate libs
on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  validate-podspec:
    name: Validate Podspec
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Podspec
        run: pod lib lint
        shell: sh

  validate-carthage:
    name: Validate Carthage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build-carthage
        shell: sh 

      - name: Archiving artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Archiving Sentry.Framework.zip
          path: Sentry.framework.zip  
