apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 1

defaults:
  timeout: 20m

xcuitest:
  app: ./DerivedData/Build/Products/Debug-iphoneos/iOS-Swift.app
  testApp: ./DerivedData/Build/Products/Debug-iphoneos/iOS-SwiftUITests-Runner.app

suites:
  - name: "iOS-Swift"
    devices:
      - name: "iPhone.*"
        orientation: "portrait"
        platformVersion: "10.3.2"
      
artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./artifacts/
