apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2

defaults:
  timeout: 20m

xcuitest:
  app: ./DerivedData/Build/Products/Debug-iphoneos/iOS-Swift.app
  testApp: ./DerivedData/Build/Products/Debug-iphoneos/iOS-SwiftUITests-Runner.app

suites:
  - name: "iOS-Swift"
    devices:
      - name: "iPhone.*"
        platformVersion: "10.3.2"
        
      - name: "iPhone.*"
        platformVersion: "11.4.1"
      
artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./artifacts/
