apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2

defaults:
  timeout: 10m

xcuitest:
  app: ./DerivedData/Build/Products/Debug-iphoneos/TrendingMovies.app
  testApp: ./DerivedData/Build/Products/Debug-iphoneos/ProfileDataGeneratorUITest-Runner.app

suites:
  - name: "High-end device"
    devices:
      - name: "iPhone .* Pro .*"
  - name: "Mid-range device"
    devices:
      - name: "iPhone 8"
        platformVersion: "14.8"
