apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2

defaults:
  timeout: 20m

xcuitest:
  app: ./DerivedData/Build/Products/Debug-iphoneos/TrendingMovies.app
  testApp: ./DerivedData/Build/Products/Debug-iphoneos/ProfileDataGeneratorUITest-Runner.app

suites:
  - name: "High-end device"
    devices:
      - name: "iPhone 13 Pro Max"
        platformVersion: "15.6"
  - name: "Mid-range device"
    devices:
      - name: "iPhone 8"
        platformVersion: "14.8"
